name: spotted
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  animate_do: ^4.2.0
  clipboard: ^0.1.3
  cloud_firestore: ^5.6.7
  cloud_functions: ^5.5.0
  connectivity_plus: ^6.1.4
  easy_image_viewer: ^1.5.1
  easy_localization: ^3.0.7+1
  firebase_analytics: ^11.4.5
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_crashlytics: ^4.3.5
  firebase_messaging: ^15.2.5
  firebase_storage: ^12.4.6
  flutter:
    sdk: flutter
  flutter_chat_core: ^2.6.1
  flutter_chat_reactions: ^0.1.1
  flutter_chat_ui: ^2.5.2
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  font_awesome_flutter: ^10.8.0
  formz: ^0.8.0
  go_router: ^15.1.2
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  multi_dropdown: ^3.0.1
  rotation_three_d_effect: ^0.2.1
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  transparent_image: ^2.0.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_flavorizr: ^2.4.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  logger: ^2.5.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/translations/

dependency_overrides:
  animate_do: ^4.2.0
