import 'package:spotted/domain/models/models.dart';

final mockUsers = [
  User(
    id: 'user_001',
    email: 'jane.doe@example.com',
    name: 'Jane',
    surname: 'Doe',
    username: 'janedoe',
    profileImageUrl: 'https://i.pravatar.cc/150?img=3',
    dateCreated: DateTime.now().subtract(const Duration(days: 120)),
    features: ['verified'],
    communitiesSubs: ['community_001'],
    friends: ['user_002', 'user_003'],
    posted: ['post_001'],
    comments: ['comment_001'],
    reactions: {'post_002': 'like'},
  ),
  User(
    id: 'user_002',
    email: 'john.smith@example.com',
    name: 'John',
    surname: 'Smith',
    username: 'johnny',
    profileImageUrl: 'https://i.pravatar.cc/150?img=5',
    dateCreated: DateTime.now().subtract(const Duration(days: 90)),
    features: [],
    communitiesSubs: ['community_002'],
    friends: ['user_001'],
    posted: ['post_002'],
    comments: ['comment_002'],
    reactions: {'post_001': 'love'},
  ),
  User(
    id: 'user_003',
    email: 'emma.lee@example.com',
    name: 'Emma',
    surname: 'Lee',
    username: 'emmalee',
    profileImageUrl: 'https://i.pravatar.cc/150?img=8',
    dateCreated: DateTime.now().subtract(const Duration(days: 45)),
    features: [],
    communitiesSubs: ['community_003'],
    friends: ['user_001'],
    posted: ['post_003'],
    comments: [],
    reactions: {},
  ),
];

final mockPosts = [
  Post(
    id: 'post_001',
    createdBy: 'user_001',
    postedIn: 'community_001',
    dateCreated: DateTime.now().subtract(const Duration(hours: 6)),
    title: 'Exploring Florence',
    content: 'The Uffizi Gallery was amazing today!',
    comments: ['comment_001'],
    pictureUrls: [],
    reactions: {'user_002': 'love', 'user_003': 'like'},
  ),
  Post(
    id: 'post_002',
    createdBy: 'user_002',
    postedIn: 'community_002',
    dateCreated: DateTime.now(),
    title: 'Morning Run',
    content: 'Ran 5k in the park, feeling refreshed!',
    comments: ['comment_002'],
    pictureUrls: [],
    reactions: {'user_001': 'like'},
  ),
  Post(
    id: 'post_003',
    createdBy: 'user_003',
    postedIn: 'community_003',
    dateCreated: DateTime.now().subtract(const Duration(days: 1)),
    title: 'Weekend Plans',
    content: 'Any suggestions for a weekend trip in Tuscany?',
    comments: [],
    pictureUrls: [],
    reactions: {},
  ),
];
