import 'package:multi_dropdown/multi_dropdown.dart';

var countryMenuItems = [
  DropdownItem(label: '🇦🇼 Aruba', value: 'Aruba'),
  DropdownItem(label: '🇦🇫 Afghanistan', value: 'Afghanistan'),
  DropdownItem(label: '🇦🇴 Angola', value: 'Angola'),
  DropdownItem(label: '🇦🇮 Anguilla', value: 'Anguilla'),
  DropdownItem(label: '🇦🇽 Åland Islands', value: 'Åland Islands'),
  DropdownItem(label: '🇦🇱 Albania', value: 'Albania'),
  DropdownItem(label: '🇦🇩 Andorra', value: 'Andorra'),
  DropdownItem(
    label: '🇦🇪 United Arab Emirates',
    value: 'United Arab Emirates',
  ),
  DropdownItem(label: '🇦🇷 Argentina', value: 'Argentina'),
  DropdownItem(label: '🇦🇲 Armenia', value: 'Armenia'),
  DropdownItem(label: '🇦🇸 American Samoa', value: 'American Samoa'),
  DropdownItem(label: '🇦🇶 Antarctica', value: 'Antarctica'),
  DropdownItem(
    label: '🇹🇫 French Southern Territories',
    value: 'French Southern Territories',
  ),
  DropdownItem(label: '🇦🇬 Antigua and Barbuda', value: 'Antigua and Barbuda'),
  DropdownItem(label: '🇦🇺 Australia', value: 'Australia'),
  DropdownItem(label: '🇦🇹 Austria', value: 'Austria'),
  DropdownItem(label: '🇦🇿 Azerbaijan', value: 'Azerbaijan'),
  DropdownItem(label: '🇧🇮 Burundi', value: 'Burundi'),
  DropdownItem(label: '🇧🇪 Belgium', value: 'Belgium'),
  DropdownItem(label: '🇧🇯 Benin', value: 'Benin'),
  DropdownItem(
    label: '🇧🇶 Bonaire, Sint Eustatius and Saba',
    value: 'Bonaire, Sint Eustatius and Saba',
  ),
  DropdownItem(label: '🇧🇫 Burkina Faso', value: 'Burkina Faso'),
  DropdownItem(label: '🇧🇩 Bangladesh', value: 'Bangladesh'),
  DropdownItem(label: '🇧🇬 Bulgaria', value: 'Bulgaria'),
  DropdownItem(label: '🇧🇭 Bahrain', value: 'Bahrain'),
  DropdownItem(label: '🇧🇸 Bahamas', value: 'Bahamas'),
  DropdownItem(
    label: '🇧🇦 Bosnia and Herzegovina',
    value: 'Bosnia and Herzegovina',
  ),
  DropdownItem(label: '🇧🇱 Saint Barthélemy', value: 'Saint Barthélemy'),
  DropdownItem(label: '🇧🇾 Belarus', value: 'Belarus'),
  DropdownItem(label: '🇧🇿 Belize', value: 'Belize'),
  DropdownItem(label: '🇧🇲 Bermuda', value: 'Bermuda'),
  DropdownItem(
    label: '🇧🇴 Bolivia, Plurinational State of',
    value: 'Bolivia, Plurinational State of',
  ),
  DropdownItem(label: '🇧🇷 Brazil', value: 'Brazil'),
  DropdownItem(label: '🇧🇧 Barbados', value: 'Barbados'),
  DropdownItem(label: '🇧🇳 Brunei Darussalam', value: 'Brunei Darussalam'),
  DropdownItem(label: '🇧🇹 Bhutan', value: 'Bhutan'),
  DropdownItem(label: '🇧🇻 Bouvet Island', value: 'Bouvet Island'),
  DropdownItem(label: '🇧🇼 Botswana', value: 'Botswana'),
  DropdownItem(
    label: '🇨🇫 Central African Republic',
    value: 'Central African Republic',
  ),
  DropdownItem(label: '🇨🇦 Canada', value: 'Canada'),
  DropdownItem(
    label: '🇨🇨 Cocos (Keeling) Islands',
    value: 'Cocos (Keeling) Islands',
  ),
  DropdownItem(label: '🇨🇭 Switzerland', value: 'Switzerland'),
  DropdownItem(label: '🇨🇱 Chile', value: 'Chile'),
  DropdownItem(label: '🇨🇳 China', value: 'China'),
  DropdownItem(label: "🇨🇮 Côte d'Ivoire", value: "Côte d'Ivoire"),
  DropdownItem(label: '🇨🇲 Cameroon', value: 'Cameroon'),
  DropdownItem(
    label: '🇨🇩 Congo, The Democratic Republic of the',
    value: 'Congo, The Democratic Republic of the',
  ),
  DropdownItem(label: '🇨🇬 Congo', value: 'Congo'),
  DropdownItem(label: '🇨🇰 Cook Islands', value: 'Cook Islands'),
  DropdownItem(label: '🇨🇴 Colombia', value: 'Colombia'),
  DropdownItem(label: '🇰🇲 Comoros', value: 'Comoros'),
  DropdownItem(label: '🇨🇻 Cabo Verde', value: 'Cabo Verde'),
  DropdownItem(label: '🇨🇷 Costa Rica', value: 'Costa Rica'),
  DropdownItem(label: '🇨🇺 Cuba', value: 'Cuba'),
  DropdownItem(label: '🇨🇼 Curaçao', value: 'Curaçao'),
  DropdownItem(label: '🇨🇽 Christmas Island', value: 'Christmas Island'),
  DropdownItem(label: '🇰🇾 Cayman Islands', value: 'Cayman Islands'),
  DropdownItem(label: '🇨🇾 Cyprus', value: 'Cyprus'),
  DropdownItem(label: '🇨🇿 Czechia', value: 'Czechia'),
  DropdownItem(label: '🇩🇪 Germany', value: 'Germany'),
  DropdownItem(label: '🇩🇯 Djibouti', value: 'Djibouti'),
  DropdownItem(label: '🇩🇲 Dominica', value: 'Dominica'),
  DropdownItem(label: '🇩🇰 Denmark', value: 'Denmark'),
  DropdownItem(label: '🇩🇴 Dominican Republic', value: 'Dominican Republic'),
  DropdownItem(label: '🇩🇿 Algeria', value: 'Algeria'),
  DropdownItem(label: '🇪🇨 Ecuador', value: 'Ecuador'),
  DropdownItem(label: '🇪🇬 Egypt', value: 'Egypt'),
  DropdownItem(label: '🇪🇷 Eritrea', value: 'Eritrea'),
  DropdownItem(label: '🇪🇭 Western Sahara', value: 'Western Sahara'),
  DropdownItem(label: '🇪🇸 Spain', value: 'Spain'),
  DropdownItem(label: '🇪🇪 Estonia', value: 'Estonia'),
  DropdownItem(label: '🇪🇹 Ethiopia', value: 'Ethiopia'),
  DropdownItem(label: '🇫🇮 Finland', value: 'Finland'),
  DropdownItem(label: '🇫🇯 Fiji', value: 'Fiji'),
  DropdownItem(
    label: '🇫🇰 Falkland Islands (Malvinas)',
    value: 'Falkland Islands (Malvinas)',
  ),
  DropdownItem(label: '🇫🇷 France', value: 'France'),
  DropdownItem(label: '🇫🇴 Faroe Islands', value: 'Faroe Islands'),
  DropdownItem(
    label: '🇫🇲 Micronesia, Federated States of',
    value: 'Micronesia, Federated States of',
  ),
  DropdownItem(label: '🇬🇦 Gabon', value: 'Gabon'),
  DropdownItem(label: '🇬🇧 United Kingdom', value: 'United Kingdom'),
  DropdownItem(label: '🇬🇪 Georgia', value: 'Georgia'),
  DropdownItem(label: '🇬🇬 Guernsey', value: 'Guernsey'),
  DropdownItem(label: '🇬🇭 Ghana', value: 'Ghana'),
  DropdownItem(label: '🇬🇮 Gibraltar', value: 'Gibraltar'),
  DropdownItem(label: '🇬🇳 Guinea', value: 'Guinea'),
  DropdownItem(label: '🇬🇵 Guadeloupe', value: 'Guadeloupe'),
  DropdownItem(label: '🇬🇲 Gambia', value: 'Gambia'),
  DropdownItem(label: '🇬🇼 Guinea-Bissau', value: 'Guinea-Bissau'),
  DropdownItem(label: '🇬🇶 Equatorial Guinea', value: 'Equatorial Guinea'),
  DropdownItem(label: '🇬🇷 Greece', value: 'Greece'),
  DropdownItem(label: '🇬🇩 Grenada', value: 'Grenada'),
  DropdownItem(label: '🇬🇱 Greenland', value: 'Greenland'),
  DropdownItem(label: '🇬🇹 Guatemala', value: 'Guatemala'),
  DropdownItem(label: '🇬🇫 French Guiana', value: 'French Guiana'),
  DropdownItem(label: '🇬🇺 Guam', value: 'Guam'),
  DropdownItem(label: '🇬🇾 Guyana', value: 'Guyana'),
  DropdownItem(label: '🇭🇰 Hong Kong', value: 'Hong Kong'),
  DropdownItem(
    label: '🇭🇲 Heard Island and McDonald Islands',
    value: 'Heard Island and McDonald Islands',
  ),
  DropdownItem(label: '🇭🇳 Honduras', value: 'Honduras'),
  DropdownItem(label: '🇭🇷 Croatia', value: 'Croatia'),
  DropdownItem(label: '🇭🇹 Haiti', value: 'Haiti'),
  DropdownItem(label: '🇭🇺 Hungary', value: 'Hungary'),
  DropdownItem(label: '🇮🇩 Indonesia', value: 'Indonesia'),
  DropdownItem(label: '🇮🇲 Isle of Man', value: 'Isle of Man'),
  DropdownItem(label: '🇮🇳 India', value: 'India'),
  DropdownItem(
    label: '🇮🇴 British Indian Ocean Territory',
    value: 'British Indian Ocean Territory',
  ),
  DropdownItem(label: '🇮🇪 Ireland', value: 'Ireland'),
  DropdownItem(
    label: '🇮🇷 Iran, Islamic Republic of',
    value: 'Iran, Islamic Republic of',
  ),
  DropdownItem(label: '🇮🇶 Iraq', value: 'Iraq'),
  DropdownItem(label: '🇮🇸 Iceland', value: 'Iceland'),
  DropdownItem(label: '🇮🇱 Israel', value: 'Israel'),
  DropdownItem(label: '🇮🇹 Italy', value: 'Italy'),
  DropdownItem(label: '🇯🇲 Jamaica', value: 'Jamaica'),
  DropdownItem(label: '🇯🇪 Jersey', value: 'Jersey'),
  DropdownItem(label: '🇯🇴 Jordan', value: 'Jordan'),
  DropdownItem(label: '🇯🇵 Japan', value: 'Japan'),
  DropdownItem(label: '🇰🇿 Kazakhstan', value: 'Kazakhstan'),
  DropdownItem(label: '🇰🇪 Kenya', value: 'Kenya'),
  DropdownItem(label: '🇰🇬 Kyrgyzstan', value: 'Kyrgyzstan'),
  DropdownItem(label: '🇰🇭 Cambodia', value: 'Cambodia'),
  DropdownItem(label: '🇰🇮 Kiribati', value: 'Kiribati'),
  DropdownItem(
    label: '🇰🇳 Saint Kitts and Nevis',
    value: 'Saint Kitts and Nevis',
  ),
  DropdownItem(label: '🇰🇷 Korea, Republic of', value: 'Korea, Republic of'),
  DropdownItem(label: '🇰🇼 Kuwait', value: 'Kuwait'),
  DropdownItem(
    label: "🇱🇦 Lao People's Democratic Republic",
    value: "Lao People's Democratic Republic",
  ),
  DropdownItem(label: '🇱🇧 Lebanon', value: 'Lebanon'),
  DropdownItem(label: '🇱🇷 Liberia', value: 'Liberia'),
  DropdownItem(label: '🇱🇾 Libya', value: 'Libya'),
  DropdownItem(label: '🇱🇨 Saint Lucia', value: 'Saint Lucia'),
  DropdownItem(label: '🇱🇮 Liechtenstein', value: 'Liechtenstein'),
  DropdownItem(label: '🇱🇰 Sri Lanka', value: 'Sri Lanka'),
  DropdownItem(label: '🇱🇸 Lesotho', value: 'Lesotho'),
  DropdownItem(label: '🇱🇹 Lithuania', value: 'Lithuania'),
  DropdownItem(label: '🇱🇺 Luxembourg', value: 'Luxembourg'),
  DropdownItem(label: '🇱🇻 Latvia', value: 'Latvia'),
  DropdownItem(label: '🇲🇴 Macao', value: 'Macao'),
  DropdownItem(
    label: '🇲🇫 Saint Martin (French part)',
    value: 'Saint Martin (French part)',
  ),
  DropdownItem(label: '🇲🇦 Morocco', value: 'Morocco'),
  DropdownItem(label: '🇲🇨 Monaco', value: 'Monaco'),
  DropdownItem(
    label: '🇲🇩 Moldova, Republic of',
    value: 'Moldova, Republic of',
  ),
  DropdownItem(label: '🇲🇬 Madagascar', value: 'Madagascar'),
  DropdownItem(label: '🇲🇻 Maldives', value: 'Maldives'),
  DropdownItem(label: '🇲🇽 Mexico', value: 'Mexico'),
  DropdownItem(label: '🇲🇭 Marshall Islands', value: 'Marshall Islands'),
  DropdownItem(label: '🇲🇰 North Macedonia', value: 'North Macedonia'),
  DropdownItem(label: '🇲🇱 Mali', value: 'Mali'),
  DropdownItem(label: '🇲🇹 Malta', value: 'Malta'),
  DropdownItem(label: '🇲🇲 Myanmar', value: 'Myanmar'),
  DropdownItem(label: '🇲🇪 Montenegro', value: 'Montenegro'),
  DropdownItem(label: '🇲🇳 Mongolia', value: 'Mongolia'),
  DropdownItem(
    label: '🇲🇵 Northern Mariana Islands',
    value: 'Northern Mariana Islands',
  ),
  DropdownItem(label: '🇲🇿 Mozambique', value: 'Mozambique'),
  DropdownItem(label: '🇲🇷 Mauritania', value: 'Mauritania'),
  DropdownItem(label: '🇲🇸 Montserrat', value: 'Montserrat'),
  DropdownItem(label: '🇲🇶 Martinique', value: 'Martinique'),
  DropdownItem(label: '🇲🇺 Mauritius', value: 'Mauritius'),
  DropdownItem(label: '🇲🇼 Malawi', value: 'Malawi'),
  DropdownItem(label: '🇲🇾 Malaysia', value: 'Malaysia'),
  DropdownItem(label: '🇾🇹 Mayotte', value: 'Mayotte'),
  DropdownItem(label: '🇳🇦 Namibia', value: 'Namibia'),
  DropdownItem(label: '🇳🇨 New Caledonia', value: 'New Caledonia'),
  DropdownItem(label: '🇳🇪 Niger', value: 'Niger'),
  DropdownItem(label: '🇳🇫 Norfolk Island', value: 'Norfolk Island'),
  DropdownItem(label: '🇳🇬 Nigeria', value: 'Nigeria'),
  DropdownItem(label: '🇳🇮 Nicaragua', value: 'Nicaragua'),
  DropdownItem(label: '🇳🇺 Niue', value: 'Niue'),
  DropdownItem(label: '🇳🇱 Netherlands', value: 'Netherlands'),
  DropdownItem(label: '🇳🇴 Norway', value: 'Norway'),
  DropdownItem(label: '🇳🇵 Nepal', value: 'Nepal'),
  DropdownItem(label: '🇳🇷 Nauru', value: 'Nauru'),
  DropdownItem(label: '🇳🇿 New Zealand', value: 'New Zealand'),
  DropdownItem(label: '🇴🇲 Oman', value: 'Oman'),
  DropdownItem(label: '🇵🇰 Pakistan', value: 'Pakistan'),
  DropdownItem(label: '🇵🇦 Panama', value: 'Panama'),
  DropdownItem(label: '🇵🇳 Pitcairn', value: 'Pitcairn'),
  DropdownItem(label: '🇵🇪 Peru', value: 'Peru'),
  DropdownItem(label: '🇵🇭 Philippines', value: 'Philippines'),
  DropdownItem(label: '🇵🇼 Palau', value: 'Palau'),
  DropdownItem(label: '🇵🇬 Papua New Guinea', value: 'Papua New Guinea'),
  DropdownItem(label: '🇵🇱 Poland', value: 'Poland'),
  DropdownItem(label: '🇵🇷 Puerto Rico', value: 'Puerto Rico'),
  DropdownItem(
    label: "🇰🇵 (Not so) Democratic People's Republic of Korea",
    value: "Democratic People's Republic of Korea",
  ),
  DropdownItem(label: '🇵🇹 Portugal', value: 'Portugal'),
  DropdownItem(label: '🇵🇾 Paraguay', value: 'Paraguay'),
  DropdownItem(label: '🇵🇸 Palestine, State of', value: 'Palestine, State of'),
  DropdownItem(label: '🇵🇫 French Polynesia', value: 'French Polynesia'),
  DropdownItem(label: '🇶🇦 Qatar', value: 'Qatar'),
  DropdownItem(label: '🇷🇪 Réunion', value: 'Réunion'),
  DropdownItem(label: '🇷🇴 Romania', value: 'Romania'),
  DropdownItem(label: '🇷🇺 Russian Federation', value: 'Russian Federation'),
  DropdownItem(label: '🇷🇼 Rwanda', value: 'Rwanda'),
  DropdownItem(label: '🇸🇦 Saudi Arabia', value: 'Saudi Arabia'),
  DropdownItem(label: '🇸🇩 Sudan', value: 'Sudan'),
  DropdownItem(label: '🇸🇳 Senegal', value: 'Senegal'),
  DropdownItem(label: '🇸🇬 Singapore', value: 'Singapore'),
  DropdownItem(
    label: '🇬🇸 South Georgia and the South Sandwich Islands',
    value: 'South Georgia and the South Sandwich Islands',
  ),
  DropdownItem(
    label: '🇸🇭 Saint Helena, Ascension and Tristan da Cunha',
    value: 'Saint Helena, Ascension and Tristan da Cunha',
  ),
  DropdownItem(
    label: '🇸🇯 Svalbard and Jan Mayen',
    value: 'Svalbard and Jan Mayen',
  ),
  DropdownItem(label: '🇸🇧 Solomon Islands', value: 'Solomon Islands'),
  DropdownItem(label: '🇸🇱 Sierra Leone', value: 'Sierra Leone'),
  DropdownItem(label: '🇸🇻 El Salvador', value: 'El Salvador'),
  DropdownItem(label: '🇸🇲 San Marino', value: 'San Marino'),
  DropdownItem(label: '🇸🇴 Somalia', value: 'Somalia'),
  DropdownItem(
    label: '🇵🇲 Saint Pierre and Miquelon',
    value: 'Saint Pierre and Miquelon',
  ),
  DropdownItem(label: '🇷🇸 Serbia', value: 'Serbia'),
  DropdownItem(label: '🇸🇸 South Sudan', value: 'South Sudan'),
  DropdownItem(
    label: '🇸🇹 Sao Tome and Principe',
    value: 'Sao Tome and Principe',
  ),
  DropdownItem(label: '🇸🇷 Suriname', value: 'Suriname'),
  DropdownItem(label: '🇸🇰 Slovakia', value: 'Slovakia'),
  DropdownItem(label: '🇸🇮 Slovenia', value: 'Slovenia'),
  DropdownItem(label: '🇸🇪 Sweden', value: 'Sweden'),
  DropdownItem(label: '🇸🇿 Eswatini', value: 'Eswatini'),
  DropdownItem(
    label: '🇸🇽 Sint Maarten (Dutch part)',
    value: 'Sint Maarten (Dutch part)',
  ),
  DropdownItem(label: '🇸🇨 Seychelles', value: 'Seychelles'),
  DropdownItem(
    label: '🇸🇾 Syrian Arab Republic',
    value: 'Syrian Arab Republic',
  ),
  DropdownItem(
    label: '🇹🇨 Turks and Caicos Islands',
    value: 'Turks and Caicos Islands',
  ),
  DropdownItem(label: '🇹🇩 Chad', value: 'Chad'),
  DropdownItem(label: '🇹🇬 Togo', value: 'Togo'),
  DropdownItem(label: '🇹🇭 Thailand', value: 'Thailand'),
  DropdownItem(label: '🇹🇯 Tajikistan', value: 'Tajikistan'),
  DropdownItem(label: '🇹🇰 Tokelau', value: 'Tokelau'),
  DropdownItem(label: '🇹🇲 Turkmenistan', value: 'Turkmenistan'),
  DropdownItem(label: '🇹🇱 Timor-Leste', value: 'Timor-Leste'),
  DropdownItem(label: '🇹🇴 Tonga', value: 'Tonga'),
  DropdownItem(label: '🇹🇹 Trinidad and Tobago', value: 'Trinidad and Tobago'),
  DropdownItem(label: '🇹🇳 Tunisia', value: 'Tunisia'),
  DropdownItem(label: '🇹🇷 Turkey', value: 'Turkey'),
  DropdownItem(label: '🇹🇻 Tuvalu', value: 'Tuvalu'),
  DropdownItem(
    label: '🇹🇼 Taiwan, Province of China',
    value: 'Taiwan, Province of China',
  ),
  DropdownItem(
    label: '🇹🇿 Tanzania, United Republic of',
    value: 'Tanzania, United Republic of',
  ),
  DropdownItem(label: '🇺🇬 Uganda', value: 'Uganda'),
  DropdownItem(label: '🇺🇦 Ukraine', value: 'Ukraine'),
  DropdownItem(
    label: '🇺🇲 United States Minor Outlying Islands',
    value: 'United States Minor Outlying Islands',
  ),
  DropdownItem(label: '🇺🇾 Uruguay', value: 'Uruguay'),
  DropdownItem(label: '🇺🇸 United States', value: 'United States'),
  DropdownItem(label: '🇺🇿 Uzbekistan', value: 'Uzbekistan'),
  DropdownItem(
    label: '🇻🇦 Holy See (Vatican City State)',
    value: 'Holy See (Vatican City State)',
  ),
  DropdownItem(
    label: '🇻🇨 Saint Vincent and the Grenadines',
    value: 'Saint Vincent and the Grenadines',
  ),
  DropdownItem(
    label: '🇻🇪 Venezuela, Bolivarian Republic of',
    value: 'Venezuela, Bolivarian Republic of',
  ),
  DropdownItem(
    label: '🇻🇬 Virgin Islands, British',
    value: 'Virgin Islands, British',
  ),
  DropdownItem(
    label: '🇻🇮 Virgin Islands, U.S.',
    value: 'Virgin Islands, U.S.',
  ),
  DropdownItem(label: '🇻🇳 Viet Nam', value: 'Viet Nam'),
  DropdownItem(label: '🇻🇺 Vanuatu', value: 'Vanuatu'),
  DropdownItem(label: '🇼🇫 Wallis and Futuna', value: 'Wallis and Futuna'),
  DropdownItem(label: '🇼🇸 Samoa', value: 'Samoa'),
  DropdownItem(label: '🇾🇪 Yemen', value: 'Yemen'),
  DropdownItem(label: '🇿🇦 South Africa', value: 'South Africa'),
  DropdownItem(label: '🇿🇲 Zambia', value: 'Zambia'),
  DropdownItem(label: '🇿🇼 Zimbabwe', value: 'Zimbabwe'),
];
